version: 2.1
jobs:
  build-and-test:
    docker:
      - image: circleci/node:12.16.2
    steps:
      - checkout
      - restore_cache:
          keys:
          - yarn-cache-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
          - yarn-cache-{{ .Branch }}-
          - yarn-cache-
      - run:
          name: yarn-install
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      - run:
          name: tests
          command: yarn --cache-folder ~/.cache/yarn test
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-cache-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
